### ISSUE TITLE
Use more data for claiming which Census programs are most popular?

### ISSUE THREAD

**Issue by arilamstein** [RConsortium/censusguide#19]
@loganpowell Currently we're using only 1 day's worth of API requests to determine which Census programs are most popular:

https://github.com/RConsortium/censusguide/blob/master/training-resources/popular-datasets.md

Is it possible to use a larger dataset, say 1 year? The reason is that some datasets might get spikes when they have, say, an annual release. When it came time to decide which R packages to highlight, I used 1 year's worth of data.

I think that what we have now is good enough to ship, especially for a v1 of this document. So if this is too much work, then feel free to just close this.

But as I'm gearing up to finalize v1 of this document (next Friday), it occurred to me that it might be good to revisit this issue.

**Comment by loganpowell** [comment]
Let me ask

**Comment by arilamstein** [comment]
Hey @loganpowell I just wanted to follow up on this, as I'm looking to complete v1 of the guide by Friday. Do you think that you'll be able to get a larger sampling by Friday?

The reason I ask is that I'm planning to complete v1 of this document by Friday. After that it will be much harder for me to incorporate changes and rewrite portions of it.

**Comment by arilamstein** [comment]
The team doesn't have bandwith right now to get us additional data.
