### ISSUE TITLE
Compile list of Census Training resources to include in the guide

### ISSUE THREAD

**Issue by arilamstein** [RConsortium/censusguide#4]

**Comment by arilamstein** [comment]
I completed this, and the files are in r-packages.csv and r-packages.html

**Comment by loganpowell** [comment]
Should I be working on this or did you close it because your satisfied with
what you have?

**Comment by arilamstein** [comment]
Sorry - I closed the wrong issue. I should have closed one saying that I now have a complete list of R packages to use in the Guide!

**Comment by loganpowell** [comment]
Ok, starting now...

**Comment by arilamstein** [comment]
@loganpowell This is great. Based on your list of API traffic= I put together a list that contains links to what I believe are the top 5 most requested datasets. I also found a URL on census.gov that contains a an exhaustive list of censuses, surveys and programs that I think would be worth including. Can you check it out and let me know what you think? Here's the file: https://github.com/RConsortium/censusguide/blob/master/census-links.md

**Comment by loganpowell** [comment]
Wow, I've never seen that list, but it is the most comprehensive list of surveys we do I've ever seen. Good find!

**Comment by arilamstein** [comment]
:)

**Comment by arilamstein** [comment]
I think that we now have enough information to close this task, and (by extension) Milestone 2 (https://github.com/RConsortium/censusguide/milestone/2).

What do you think?

After completing this milestone I said that I would write a blog post about the project, and give the larger community a chance to provide feedback on the resources we're planning to include in the Guide.
