### ISSUE TITLE
Title seems wrong

### ISSUE THREAD

**Issue by arilamstein** [RConsortium/censusguide#69]
If you visit the web page for this repo (Written by the R Consortium Census Working Group) the title says "Written by the R Consortium Census Working Group".

I believe that this is a bug. I think that we want the title to be "A Guide to Working with Census Data in R".

It looks like this title comes from the title of the README. So we probably want to make the first line a h1 like `# A Guide to Working with Census Data in R` and then maybe below that a h3 that says something like `### Written by the R Consortium Census Working Group`.

**Comment by ccStan** [comment]
I agree. A better title would be, "Written by the R Consortium Census Working Group". This title might also lead analysts who are working in other platforms such as SAS or Tableau to have a look.

 

Best Regards,

Stan Siranovich

Principal Analyst

 

Cell: 1-502-409-2370

Office: 1-812-913-4507

Profile:  <https://www.linkedin.com/in/stansiranovich/> LinkedIn



 

From: Ari Lamstein ***@***.*** 
Sent: Monday, September 9, 2024 2:11 PM
To: RConsortium/censusguide ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RConsortium/censusguide] Title seems wrong (Issue #69)

 

If you visit the web page for this repo (Written by the R Consortium Census Working Group) the title says "Written by the R Consortium Census Working Group".

I believe that this is a bug. I think that we want the title to be "A Guide to Working with Census Data in R".

It looks like this title comes from the title of the README. So we probably want to make the first line a h1 like # A Guide to Working with Census Data in R and then maybe below that a h3 that says something like ### Written by the R Consortium Census Working Group.

**Comment by JessMK** [comment]
Great catch! I have updated the title to "A Guide to Working with Census Data in R", and we can update this to include other platforms if we expand in the future.

**Comment by arilamstein** [comment]
I approved the PR and verified that it is now showing up correctly on the website: https://rconsortium.github.io/censusguide/
